### PR TITLE
testing in stage now. 

### PR DESCRIPTION
**Pull request by matt-matsuoka**

### CODE REVIEW

**Comment by matt-matsuoka** [comment]
Adding GDPR banner.

**Comment by matt-matsuoka** [comment]
Jonathan, 

Vishal created a GDPR banner for RAML. I tested it locally and now want to view it on staging. 

Thanks,

Matt

**Review by jstoiko — COMMENTED** [review]
Question: does this display for any user or only users from EU? If the former, is there a way to make it only display to EU users?

**Comment by matt-matsuoka** [comment]
Jonathan,

We can't do that. The reason is is the law is not limited to people viewing sites in the EU, but EU citizens who might be traveling abroad as well. I have no way of knowing if someone is in the EU explicitly. 

Matt

**Pull request merged**
