### PR TITLE
adding RAML API Tester project

### PR DESCRIPTION
**Pull request by mafischer**
I just setup this project. It's purpose is to generate api requests and test a server that implements a raml spec.

### CODE REVIEW

**Review by jstoiko — APPROVED** [review]

**Comment by jstoiko** [comment]
@mafischer: I am curious, how does this compare to https://github.com/mulesoft-labs/osprey-mock-service?

btw, are you on the RAML Slack? if not, feel free to join our group: https://raml.org/slack

**Comment by mafischer** [comment]
Based on my understanding of osprey the difference is that osprey is creating a mock server whereas this is creating a mock client.

This tool is intended to validate that a server is correctly implementing it's raml spec.

**Comment by jstoiko** [comment]
Gotcha. It sounds dangerous 😳. Although I am sure there are situations where this could be useful, like e2e tests for example, would you say that's the most realistic use case scenario?

**Review by jstoiko — APPROVED** [review]

**Comment by mafischer** [comment]
Yes, e2e tests would be a primary use case, as well as load testing.

**Pull request merged**
