### PR TITLE
remove duplicate project

### PR DESCRIPTION
**Pull request by jenschude**
This entry was incorrect and is a duplicate of the raml-php-generator entry

### CODE REVIEW

**Comment by sichvoge** [comment]
Damn, I think that should actually point to  https://github.com/mulesoft-labs/raml-javascript-generator and author should be "MuleSoft".

Would you be so kind and change your PR and put these values in?

**Comment by jenschude** [comment]
@sichvoge done 👍

**Comment by sichvoge** [comment]
Perfect! thanks!

**Review by sichvoge — APPROVED** [review]
LGTM 👍

**Pull request merged**
