### PR TITLE
RAML-to-Swagger2-Converter-Java

### PR DESCRIPTION
**Pull request by esh-b**
- It is a java project which converts RAML 0.8 version of API definitions to Swagger 2.0 API definitions. This ensures RAML's backward compatibility with Swagger. Java is being used by majority of the corporate companies. So, this java project might help them to do the interconversion with ease.

- All the dependencies, examples and the instructions to run the project are described in the readme.md file in the project directory.

Regards,
Eshwanth.

### CODE REVIEW

**Review by sichvoge — APPROVED** [review]
LGTM 👍

**Comment by sichvoge** [comment]
Thanks @esh-b.

**Comment by sichvoge** [comment]
OH, can you point your branch against the `stg` branch, please?

**Comment by esh-b** [comment]
@sichvoge so, should I make changes to stg branch's projects.yml file and send a PR again?

**Comment by esh-b** [comment]
@sichvoge so, you want me to send a PR after adding the project to projects.yml to the `stg` branch instead of `prd` branch?

**Comment by sichvoge** [comment]
Yes,  but against `develop` please.

**Pull request closed without merging**
