### PR TITLE
Partially fixes #86: Projects

### LINKED ISSUE #86: New 2019 website checklist
Projects:
- [x] add `secondary_link` where possible ([E.g.](https://github.com/raml-org/raml-org/blob/develop/_data/projects.yml#L53))
- [x] review projects [submitted as PRs](https://github.com/raml-org/raml-org/pulls)
- [x] review list of projects, add new projects (make PR)

Playground:
- [x] Rename button next to Monaco editor "Fullscreen" to "Try it out"
- [x] Link both "Try it out" buttons to playground demo
- [x] Pass content of Monaco editor to playground demo

### PR DESCRIPTION
**Pull request by postatum**
Fixes `Project` tasks list from #86

### CODE REVIEW

**Review by jstoiko — CHANGES_REQUESTED** [review]
We should probably mark the projects that are no longer maintained as such. E.g. `API Workbench -> API Workbench (deprecated)`. That's one I know of, are there others?

**Comment by postatum** [comment]
> We should probably mark the projects that are no longer maintained as such. E.g. `API Workbench -> API Workbench (deprecated)`. That's one I know of, are there others?

@jstoiko Fixed. Please re-review.

**Review by jstoiko — CHANGES_REQUESTED** [review]
Looking good. I like the "deprecated" flag idea, it's better that doing it straight in the title. I can also mark both JS and Java parsers as deprecated for now. The rest (if any come up in the future as becoming "deprecated") we can always add later.

**Comment by postatum** [comment]
> Looking good. I like the "deprecated" flag idea, it's better that doing it straight in the title. I can also mark both JS and Java parsers as deprecated for now. The rest (if any come up in the future as becoming "deprecated") we can always add later.

I've just marked Java parser as deprecated, js parser is already marked. Is that all the changes you requested?

**Review by jstoiko — APPROVED** [review]

**Comment by jstoiko** [comment]
@postatum: I think we can now merge this into `develop` (and any other development branches that rely on the new design). 

Can you also merge the updated `_projects.yml` file into `prd`? I don't think the added metadata (e.g. `secondary_link` and `deprecated`) will break things but if it does, simply remove that extra metadata from that `prd` version...

**Comment by postatum** [comment]
> @postatum: I think we can now merge this into `develop` (and any other development branches that rely on the new design).
> 
> Can you also merge the updated `_projects.yml` file into `prd`? I don't think the added metadata (e.g. `secondary_link` and `deprecated`) will break things but if it does, simply remove that extra metadata from that `prd` version...

Done except for `prd` merge because pushes to it require a review. Created PR here https://github.com/raml-org/raml-org/pull/93

**Comment by jstoiko** [comment]
@postatum: one thing I just realized I had missed is why all those `deprecated: false`? can we get rid of this and we can simply assume that it's false if it's not there...

**Comment by postatum** [comment]
> @postatum: one thing I just realized I had missed is why all those `deprecated: false`? can we get rid of this and we can simply assume that it's false if it's not there...

yes

**Pull request merged**
